# Generated by Django 3.2.4 on 2023-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_googleadsaccountcreation_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCreateCampaignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytoken', models.CharField(max_length=500)),
                ('refreshToken', models.CharField(max_length=500)),
                ('login_customer_id', models.CharField(max_length=500)),
                ('keyword_text', models.CharField(max_length=2500)),
                ('free_form_text', models.CharField(max_length=5000)),
                ('business_location_id', models.CharField(max_length=500)),
                ('business_profile_name', models.CharField(max_length=500)),
            ],
        ),
    ]
