# Generated by Django 3.2.4 on 2023-12-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adgroup_name', models.CharField(max_length=500)),
                ('campaign_id', models.CharField(max_length=30)),
                ('customer_id', models.CharField(max_length=500)),
                ('bid_amount', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CreateCampaignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mytoken', models.CharField(max_length=500)),
                ('budget', models.PositiveIntegerField()),
                ('campaign_name', models.CharField(max_length=500)),
                ('customer_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('refresh_token', models.CharField(max_length=500)),
                ('google_access_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
